<a href="https://colab.research.google.com/github/veruizr/ML_Doc/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy
Numpy es una librería aplicada para el manejo de vectores y matrices, que facilita una gran cantidad de operaciones matemáticas que pueden resolverse mediante el álgebra matricial ayudando a resolver aspectos como:
- Matrices multidimensionales (ndarray) eficientes.
- Operaciones matemáticas rápidas.
- Funciones de álgebra lineal, transformadas de Fourier, generación de números aleatorios, entre otras.

Para instalar NumPy:

In [1]:
#pip install numpy
import numpy as np

## Creación y Manipulación de Matrices (Arrays)

### Crear Matrices (Arrays)

### Matriz unidimensional

In [2]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


### Matriz n-dimensional

In [3]:
b = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Matriz de ceros

In [4]:
zeros = np.zeros((3, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Matriz de unos

In [6]:
ones = np.ones((4, 4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Matriz de valores equidistantes

In [7]:
lin_space = np.linspace(0, 10, 5) # De 0 a 10 en 5 puntos
print(lin_space)

[ 0.   2.5  5.   7.5 10. ]


##Indexación y Segmentación

In [8]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

# Acceder a un elemento específico
print(arr[1, 2])

60


In [9]:
# Extraer una fila
print(arr[1, :])

[40 50 60]


In [10]:
# Extraer una columna
print(arr[:, 1])

[20 50 80]


## Operaciones con Matrices

### Operaciones Básicas

In [11]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Suma
print(A + B)

[[ 6  8]
 [10 12]]


In [12]:
# Resta
print(A - B)

[[-4 -4]
 [-4 -4]]


In [13]:
# Multiplicación elemento a elemento
print(A * B)

[[ 5 12]
 [21 32]]


In [14]:
# Producto de matrices (matmul o @)
print(np.matmul(A, B))
print(A @ B)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [15]:
# Transpuesta
print(A.T)

[[1 3]
 [2 4]]


### Determinante e Inversa

In [ ]:
from numpy.linalg import det, inv

A = np.array([[4, 7], [2, 6]])

# Determinante
print(det(A))

In [ ]:
# Matriz inversa
print(inv(A))

## Solución de Sistemas de Ecuaciones Lineales
Resolver el sistema:

\[ 2x + 3y = 5 \]
\[ 4x + y = 6 \]

In [ ]:
# Matriz de coeficientes
A = np.array([[2, 3], [4, 1]])

# Vector de términos independientes
b = np.array([5, 6])

# Resolver el sistema
x = np.linalg.solve(A, b)
print("Solución:", x)

## Álgebra Vectorial



In [16]:
# Producto punto
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

print(np.dot(u, v)) # 1*4 + 2*5 + 3*6 = 32

32


In [17]:
#Producto cruz
u = np.array([1, 0, 0])
v = np.array([0, 1, 0])

print(np.cross(u, v)) # [0, 0, 1]

[0 0 1]


In [18]:
#Norma de un vector
v = np.array([3, 4])

print(np.linalg.norm(v))

5.0
